-- Supprimer d'abord les tables dépendantes
DROP TABLE IF EXISTS Log_Activite CASCADE;
DROP TABLE IF EXISTS Password_Reset CASCADE;
DROP TABLE IF EXISTS Session CASCADE;
DROP TABLE IF EXISTS Consentement CASCADE;
DROP TABLE IF EXISTS Cible_Notifications CASCADE;
DROP TABLE IF EXISTS Notifications CASCADE;
DROP TABLE IF EXISTS Historique_fidelite CASCADE;
DROP TABLE IF EXISTS Paiement CASCADE;
DROP TABLE IF EXISTS Concerner_menu CASCADE;
DROP TABLE IF EXISTS Etre_livreur CASCADE;
DROP TABLE IF EXISTS Gerer CASCADE;
DROP TABLE IF EXISTS Travailler_pour CASCADE;
DROP TABLE IF EXISTS Contenir CASCADE;
DROP TABLE IF EXISTS Choisir_Menu_Jour CASCADE;
DROP TABLE IF EXISTS Noter CASCADE;
DROP TABLE IF EXISTS Reponse CASCADE;
DROP TABLE IF EXISTS Reclamation CASCADE;
DROP TABLE IF EXISTS Promotion CASCADE;
DROP TABLE IF EXISTS Livraison CASCADE;
DROP TABLE IF EXISTS Bon_commande CASCADE;
DROP TABLE IF EXISTS Commande CASCADE;
DROP TABLE IF EXISTS Menu CASCADE;
DROP TABLE IF EXISTS Categorie_menu CASCADE;
DROP TABLE IF EXISTS Restaurant CASCADE;

-- Supprimer les tables liées aux utilisateurs
DROP TABLE IF EXISTS Livreur CASCADE;
DROP TABLE IF EXISTS Employe CASCADE;
DROP TABLE IF EXISTS Gerant CASCADE;
DROP TABLE IF EXISTS Administrateur CASCADE;
DROP TABLE IF EXISTS Client CASCADE;
DROP TABLE IF EXISTS Utilisateur CASCADE;

-- Supprimer les fichiers si présents
DROP TABLE IF EXISTS File CASCADE;